DROP INDEX IF EXISTS NYC_PART_NUMBER;
DROP INDEX IF EXISTS SFO_PART_NUMBER;
DROP INDEX IF EXISTS TOTAL_SUPPLIER_ID;
DROP INDEX IF EXISTS TOTAL_SUPPLIER_NAME;
DROP INDEX IF EXISTS TOTAL_COLOR_ID;
DROP INDEX IF EXISTS TOTAL_COLOR_NAME;

CREATE INDEX NYC_PART_NUMBER
ON PART_NYC
USING btree (PART_NUMBER);


CREATE INDEX SFO_PART_NUMBER
ON PART_SFO
USING btree (PART_NUMBER);


CREATE INDEX TOTAL_SUPPLIER_ID
ON SUPPLIER
USING btree (SUPPLIER_ID);


CREATE INDEX TOTAL_SUPPLIER_NAME
ON SUPPLIER
USING btree (SUPPLIER_NAME);


CREATE INDEX TOTAL_COLOR_ID
ON COLOR
USING btree (COLOR_ID);


CREATE INDEX TOTAL_COLOR_NAME
ON COLOR
USING btree (COLOR_NAME);

